#include                "a_samp.inc"
#include                "zCMD.inc"
#include                "zcmd.inc"
#include                "ZCMD.inc"
#include                "SetVehicleAttachedObject.inc"
#include                "float.inc"
#include                "streamer.inc"
#include                "mSelection.inc"
#include                "progress.inc"
#include                "sscanf2.inc"
#include                "core"
#include                "mailer.inc"
#include                <a_mysql>
#include <dof2>

//Modules
//--------  CONFIG	-------//
#include "../gamemodes/config.pwn"
#include "../modules/global/dialogs.pwn"
//--------	Modules -------//
#include "../modules/global/mysql.pwn"
#include "../modules/global/variaveis.pwn" //Variaveis globais
#include "../modules/global/includes.pwn"  //Includes globais
#include "../modules/player/variaveis.pwn" //Variaveis player
#include "../modules/player/includes.pwn" //players
#include "../modules/global/includes.pwn" //global